export const CYCLE_STAGES = {
  STARTING: 'starting',
  SYNCING_BROKER: 'syncing_broker',
  MONITORING_POSITIONS: 'monitoring_positions',
  FETCHING_MARKET_DATA: 'fetching_market_data',
  // v2 pipeline stages
  PRE_FILTERING: 'pre_filtering',
  SCORING_CANDIDATES: 'scoring_candidates',
  SHORTLISTING: 'shortlisting',
  EVALUATING_SIGNALS: 'evaluating_signals',
  RANKING_CANDIDATES: 'ranking_candidates',
  APPLYING_RISK_GUARDS: 'applying_risk_guards',
  PLACING_ORDERS: 'placing_orders',
  FINAL_SYNC: 'final_sync',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

export const ORDERED_CYCLE_STAGES = [
  CYCLE_STAGES.STARTING,           // 0%
  CYCLE_STAGES.SYNCING_BROKER,     // 11%
  CYCLE_STAGES.MONITORING_POSITIONS, // 22%
  CYCLE_STAGES.FETCHING_MARKET_DATA, // 33%
  CYCLE_STAGES.PRE_FILTERING,      // 38%
  CYCLE_STAGES.SCORING_CANDIDATES, // 44%
  CYCLE_STAGES.SHORTLISTING,       // 50%
  CYCLE_STAGES.EVALUATING_SIGNALS, // 56%
  CYCLE_STAGES.RANKING_CANDIDATES, // 62%
  CYCLE_STAGES.APPLYING_RISK_GUARDS, // 70%
  CYCLE_STAGES.PLACING_ORDERS,     // 80%
  CYCLE_STAGES.FINAL_SYNC,         // 90%
  CYCLE_STAGES.COMPLETED,          // 100%
];

// Manual progress overrides for stages that don't fall on even intervals.
const STAGE_PROGRESS = {
  [CYCLE_STAGES.STARTING]: 0,
  [CYCLE_STAGES.SYNCING_BROKER]: 11,
  [CYCLE_STAGES.MONITORING_POSITIONS]: 22,
  [CYCLE_STAGES.FETCHING_MARKET_DATA]: 33,
  [CYCLE_STAGES.PRE_FILTERING]: 38,
  [CYCLE_STAGES.SCORING_CANDIDATES]: 44,
  [CYCLE_STAGES.SHORTLISTING]: 50,
  [CYCLE_STAGES.EVALUATING_SIGNALS]: 56,
  [CYCLE_STAGES.RANKING_CANDIDATES]: 62,
  [CYCLE_STAGES.APPLYING_RISK_GUARDS]: 70,
  [CYCLE_STAGES.PLACING_ORDERS]: 80,
  [CYCLE_STAGES.FINAL_SYNC]: 90,
  [CYCLE_STAGES.COMPLETED]: 100,
  [CYCLE_STAGES.FAILED]: 100,
};

export function stageToProgress(stage) {
  if (stage in STAGE_PROGRESS) return STAGE_PROGRESS[stage];
  const index = ORDERED_CYCLE_STAGES.indexOf(stage);
  if (index === -1) return 0;
  return Math.round((index / (ORDERED_CYCLE_STAGES.length - 1)) * 100);
}
